travis:
  secure:
    BINSTAR_TOKEN: qaqE9WDP6a63nSvxA+rBxvVHheucs9WeELC1ZBRxNjsviGdf67ih9i+I6RbbkIUpFauPzqAc1xU19v8J7OyjWF6qfxkqaNPaw1fZALlYvcUVfHJtcXdP2BB7uD83rPQhHKi+aZiQ2vW2YmV+LFx81Absq73Pn5l1FntTmCSb576hpXBnV9dXkleDB3jY+UFLax/0qkt3oepHxq4+Qyc4z/9Y3gqDHn7M+v74WNiJsXJb8y3Z0koSzSpntMCSSltVXgJ/mIrA5wl+y34ISZPcG5+xst+VGVwX/BTrCoJAK49eYP5epd3xmtqnjqp55oYvjW+HRjc8uZljhSrUkPTXgy/uO1VicRz7zE3rAE/AO+KjEegeUzUzOQpdf4H1iChxWZU93Yr+ALKKCYXEGmXBf5cXbCTRzjkzdAqI9sAu2azkTJJgOSu/43Qfd3y+PhgKA7uJ8pL67MfoMjjNbgsXDDDBtsc1JffK3URN64K1ruVS4Vf6PpINum+q+ck+cPSpJmYZL+9ms8U2lCR7LYLRX3/HoCfX5Tir0eJe4rE7mI7ax5m96DYEVxENNPlL3gI2mpy9V7jhKKDtxKsKKAf8qFoTPPAxYVy8Pan8GYFAAmTHpKuKWTR0cqiaOkVlrPt/SaeDJAyfAr6vzcbDZr+YGzz25HnCGLuB4CjEaXTEWdw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
